name: analyze_sarif
description: Converts the output of "dart analyze --format=json" to SARIF.
version: 0.0.1
repository: https://github.com/ls1intum/dart_analyze_sarif

executables:
  analyze_sarif:

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ^7.3.0
  args: ^2.5.0
  parselyzer: ^0.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
